job_board_index:
    path:     /
    defaults: { _controller: JobBoardBundle:Default:index }
job_board_edit:
    path:     /edit/{id}
    defaults: { _controller: JobBoardBundle:Default:edit }
    requirements:
        id: '\d+'
job_board_view:
    path:     /advert/{id}
    defaults: { _controller: JobBoardBundle:Default:view }
    requirements:
        id: '\d+'
job_board_apply:
    path:     /apply/{id}
    defaults: { _controller: JobBoardBundle:Default:apply }
    requirements:
        id: '\d+'
job_board_delete:
    path:     /delete/{id}
    defaults: { _controller: JobBoardBundle:Default:delete }
    requirements:
        id: '\d+'

show_mycv:
    path:     /cv
    defaults: { _controller: JobBoardBundle:CVController:showCv }
show_othercv:
    path:     /cv/user/{userId}
    defaults: { _controller: JobBoardBundle:CVController:showCv }
edit_cv:
    path:     /cv/edit
    defaults: { _controller: JobBoardBundle:CVController:editCv }
edit_formation:
    path: /cv/edit/formation/{id}
    defaults: { _controller: JobBoardBundle:CVController:editFormation }
    requirements:
        id: '\d+'
edit_competence:
    path: /cv/edit/competence/{id}
    defaults: { _controller: JobBoardBundle:CVController:editCompetence }
    requirements:
        id: '\d+'
edit_experience:
    path: /cv/edit/experience/{id}
    defaults: { _controller: JobBoardBundle:CVController:editExperience }
    requirements:
        id: '\d+'