<?php

namespace JobBoardBundle\Repository;

/**
 * ExperienceProfessionnelleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ExperienceProfessionnelleRepository extends \Doctrine\ORM\EntityRepository
{
}
