<?php

namespace JobBoardBundle\Repository;

/**
 * InfoCVRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class InfoCVRepository extends \Doctrine\ORM\EntityRepository
{
}
